mindmap
  root((Haalbaarheid Nextcloud))
    ::icon(fa fa-cloud)
    **1. Juridische Haalbaarheid**
      ::icon(fa fa-gavel)
      AVG-Conformiteit
        ::icon(fa fa-check-circle)
        (Grondslagen, Beginselen)
      Datasoevereiniteit
        ::icon(fa fa-shield-alt)
        (Controle vs. Data-residentie)
      Extraterritoriale Wetgeving
        ::icon(fa fa-globe)
        (CLOUD Act vs. Schrems II)
    **2. Technische Robuustheid**
      ::icon(fa fa-cogs)
      Security & Privacy by Design
        ::icon(fa fa-lock)
        (Proactief, Ingebouwd)
      Normenkaders (Operationalisering)
        ::icon(fa fa-list-alt)
        BIO (Baseline Overheid)
        NIS2 (Zorg- & Meldplicht)
    **3. Organisatorische Adoptie**
      ::icon(fa fa-users)
      Technologieacceptatie (TAM)
        ::icon(fa fa-user-check)
        (Nut & Gebruiksgemak)
      Strategische Keuze
        ::icon(fa fa-chess-knight)
        (Vendor Lock-in vs. Open Source)
      Verandermanagement
        ::icon(fa fa-sync-alt)
        (Kotter's 8 Stappen)
